version: '3.5'

services: 

    mysql:
        image: sneyd321/mysql
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD:Homeowner
        cap_add:
            - SYS_NICE

  
            

 
    