name: Run Tests
on: 
  workflow_dispatch:
    inputs:
      zone:
        description: 'GCP Zone'     
        required: true
        default: 'us-east5-a'
      image:
        description: 'Docker image that will be build, pushed and deployed on cloud run'     
        required: true
        default: 'tenant-service'
      test-module:
        description: 'File containing tests for pytest to execute'     
        required: true
        default: 'tests/test_repository.py'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/959426188245/locations/global/workloadIdentityPools/github-action-pool-1/providers/github-action-provider-1'
          service_account: 'artifact-repository-access@roomr-222721.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.0
      
      - name: Terraform Init
        id: init
        run: terraform init    
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var="project_id"=roomr-222721 -var="db_pass"=root
        continue-on-error: true
      
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="project_id"=roomr-222721 -var="db_pass"=root
      
      - name: Sleep for 30 seconds to allow VM to boot container
        run: sleep 30s
        shell: bash

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install alembic dependencies
        run: |
          python -m pip install --upgrade pip
          pip install alembic
          pip install aiomysql
          pip install cryptography
          pip install passlib

      - name: Run Test
        run: |
          RANDOM_ID=$(terraform output random_id) | tr -d '"'
          echo $RANDOM_ID
          PUBLIC_IP=$(gcloud compute instances describe mysql-test-instance-$RANDOM_ID --zone=${{ github.event.inputs.zone }} --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
          echo $PUBLIC_IP
          docker build -t sneyd321/${{ github.event.inputs.image }} .  
          python alembic_setup.py --user=root --password=root --database=roomr --host=$PUBLIC_IP
          alembic revision --autogenerate
          alembic upgrade head
          docker compose run -eDB_HOST=$PUBLIC_IP ${{ github.event.inputs.image }} pytest ${{ github.event.inputs.test-module }}
      
      - name: Terraform Destroy
        if: always()
        run: terraform destroy -auto-approve -var="project_id"=roomr-222721 -var="db_pass"=root
